package cli

import (
	"crypto/ed25519"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

type spoolTrustFile struct {
	RequireSignature  bool                `json:"require_signature"`
	AllowedPublishers string              `json:"allowed_publishers"`
	Keys              []spoolTrustKeyMeta `json:"keys"`
}

type spoolTrustKeyMeta struct {
	ID          string `json:"id"`
	Label       string `json:"label"`
	Fingerprint string `json:"fingerprint"`
	Filename    string `json:"filename"`
	AddedAt     string `json:"added_at"`
}

func spoolTrustRoot() string {
	if v := strings.TrimSpace(os.Getenv("ADMIN_UI_SPOOL_TRUST_DIR")); v != "" {
		return v
	}
	if keys := strings.TrimSpace(os.Getenv("MUXCORE_SPOOL_TRUSTED_KEYS_DIR")); keys != "" {
		return filepath.Dir(keys)
	}
	return filepath.Join(os.TempDir(), "muxcore-spool-trust")
}

func spoolTrustJSONPath() string  { return filepath.Join(spoolTrustRoot(), "trust.json") }
func spoolTrustKeysDir() string   { return filepath.Join(spoolTrustRoot(), "keys") }
func spoolTrustEnvPath() string   { return filepath.Join(spoolTrustRoot(), "spool-trust.env") }

func loadSpoolTrust() spoolTrustFile {
	raw, err := os.ReadFile(spoolTrustJSONPath())
	if err != nil {
		return spoolTrustFile{}
	}
	var t spoolTrustFile
	if json.Unmarshal(raw, &t) != nil || t.Keys == nil {
		t.Keys = nil
	}
	return t
}

func saveSpoolTrust(t spoolTrustFile) error {
	if err := os.MkdirAll(spoolTrustKeysDir(), 0o700); err != nil {
		return err
	}
	raw, err := json.MarshalIndent(t, "", "  ")
	if err != nil {
		return err
	}
	tmp := spoolTrustJSONPath() + ".tmp"
	if err := os.WriteFile(tmp, raw, 0o600); err != nil {
		return err
	}
	if err := os.Rename(tmp, spoolTrustJSONPath()); err != nil {
		return err
	}
	req := "0"
	if t.RequireSignature {
		req = "1"
	}
	var b strings.Builder
	b.WriteString("# Generated by muxcorectl marketplace trust.\n")
	fmt.Fprintf(&b, "MUXCORE_SPOOL_REQUIRE_SIGNATURE=%s\n", req)
	fmt.Fprintf(&b, "MUXCORE_SPOOL_TRUSTED_KEYS_DIR=%s\n", spoolTrustKeysDir())
	if strings.TrimSpace(t.AllowedPublishers) != "" {
		fmt.Fprintf(&b, "MUXCORE_SPOOL_ALLOWED_PUBLISHERS=%s\n", strings.TrimSpace(t.AllowedPublishers))
	}
	tmpEnv := spoolTrustEnvPath() + ".tmp"
	if err := os.WriteFile(tmpEnv, []byte(b.String()), 0o600); err != nil {
		return err
	}
	return os.Rename(tmpEnv, spoolTrustEnvPath())
}

func fingerprintPub(pub ed25519.PublicKey) string {
	sum := sha256.Sum256(pub)
	return hex.EncodeToString(sum[:8])
}

func parseSpoolPublicKey(raw []byte) (ed25519.PublicKey, error) {
	if len(raw) == ed25519.PublicKeySize {
		out := make(ed25519.PublicKey, ed25519.PublicKeySize)
		copy(out, raw)
		return out, nil
	}
	s := strings.TrimSpace(string(raw))
	if dec, err := hex.DecodeString(s); err == nil && len(dec) == ed25519.PublicKeySize {
		return ed25519.PublicKey(dec), nil
	}
	if block, _ := pem.Decode(raw); block != nil && len(block.Bytes) == ed25519.PublicKeySize {
		return ed25519.PublicKey(block.Bytes), nil
	}
	return nil, fmt.Errorf("unsupported public key format")
}

func newMarketplaceTrustCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "trust",
		Short: "Spool signature trust settings (admin-ui /marketplace/trust parity)",
	}
	cmd.AddCommand(newMarketplaceTrustShowCmd())
	cmd.AddCommand(newMarketplaceTrustSettingsCmd())
	cmd.AddCommand(newMarketplaceTrustKeysAddCmd())
	cmd.AddCommand(newMarketplaceTrustKeysRevokeCmd())
	return cmd
}

func newMarketplaceTrustShowCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "show",
		Short: "Show trust settings and keys",
		RunE: func(cmd *cobra.Command, args []string) error {
			t := loadSpoolTrust()
			if flagJSON {
				return printJSON(map[string]any{
					"dir": spoolTrustRoot(), "require_signature": t.RequireSignature,
					"allowed_publishers": t.AllowedPublishers, "keys": t.Keys,
				})
			}
			fmt.Printf("dir:                 %s\n", spoolTrustRoot())
			fmt.Printf("require_signature:   %t\n", t.RequireSignature)
			fmt.Printf("allowed_publishers:  %s\n", t.AllowedPublishers)
			rows := make([][]string, 0, len(t.Keys))
			for _, k := range t.Keys {
				rows = append(rows, []string{k.ID, k.Label, k.Fingerprint, k.AddedAt})
			}
			if err := printTable([]string{"ID", "LABEL", "FINGERPRINT", "ADDED"}, rows); err != nil {
				return err
			}
			return nil
		},
	}
}

func newMarketplaceTrustSettingsCmd() *cobra.Command {
	var require bool
	var publishers string
	cmd := &cobra.Command{
		Use:   "settings",
		Short: "Update trust settings",
		RunE: func(cmd *cobra.Command, args []string) error {
			t := loadSpoolTrust()
			if cmd.Flags().Changed("require-signature") {
				t.RequireSignature = require
			}
			if cmd.Flags().Changed("allowed-publishers") {
				t.AllowedPublishers = strings.TrimSpace(publishers)
			}
			if err := saveSpoolTrust(t); err != nil {
				return fmt.Errorf("marketplace trust settings: %w", err)
			}
			if !flagQuiet {
				fmt.Println("saved")
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&require, "require-signature", false, "require signed spool tags")
	cmd.Flags().StringVar(&publishers, "allowed-publishers", "", "comma-separated publisher allowlist")
	return cmd
}

func newMarketplaceTrustKeysAddCmd() *cobra.Command {
	var label string
	cmd := &cobra.Command{
		Use:   "add <public-key-file>",
		Short: "Add a trusted publisher public key",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			raw, err := os.ReadFile(args[0])
			if err != nil {
				return fmt.Errorf("read key: %w", err)
			}
			pub, err := parseSpoolPublicKey(raw)
			if err != nil {
				return fmt.Errorf("invalid public key: %w", err)
			}
			fp := fingerprintPub(pub)
			id := fp
			if label == "" {
				label = "key-" + fp[:8]
			}
			filename := id + ".pub"
			if err := os.MkdirAll(spoolTrustKeysDir(), 0o700); err != nil {
				return err
			}
			material := strings.TrimSpace(string(raw))
			if !strings.HasSuffix(material, "\n") {
				material += "\n"
			}
			if err := os.WriteFile(filepath.Join(spoolTrustKeysDir(), filename), []byte(material), 0o600); err != nil {
				return err
			}
			t := loadSpoolTrust()
			for _, existing := range t.Keys {
				if existing.Fingerprint == fp {
					return fmt.Errorf("key already trusted (fingerprint %s)", fp)
				}
			}
			t.Keys = append(t.Keys, spoolTrustKeyMeta{
				ID: id, Label: label, Fingerprint: fp, Filename: filename,
				AddedAt: time.Now().UTC().Format(time.RFC3339),
			})
			if err := saveSpoolTrust(t); err != nil {
				return err
			}
			if flagJSON {
				return printJSON(map[string]string{"id": id, "fingerprint": fp})
			}
			if !flagQuiet {
				fmt.Printf("added key %s (%s)\n", id, fp)
			}
			return nil
		},
	}
	cmd.Flags().StringVar(&label, "label", "", "human-readable label")
	return cmd
}

func newMarketplaceTrustKeysRevokeCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "revoke <key-id>",
		Short: "Revoke a trusted key",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			t := loadSpoolTrust()
			var kept []spoolTrustKeyMeta
			var removed *spoolTrustKeyMeta
			for i := range t.Keys {
				if t.Keys[i].ID == args[0] {
					removed = &t.Keys[i]
					continue
				}
				kept = append(kept, t.Keys[i])
			}
			if removed == nil {
				return fmt.Errorf("key %q not found", args[0])
			}
			t.Keys = kept
			if err := saveSpoolTrust(t); err != nil {
				return err
			}
			_ = os.Remove(filepath.Join(spoolTrustKeysDir(), removed.Filename))
			if !flagQuiet {
				fmt.Println("revoked")
			}
			return nil
		},
	}
}
